spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie